### ISSUE TITLE
Race Conditions in Learning Code people might use as examples.

### ISSUE THREAD

**Issue by daveb68x** [google-developer-training/android-fundamentals-apps-v2#14]
From code lab 7.2 -- WhoWroteIt

Is it my ignorance or is this code going to crash intermittently based on race conditions.

    } catch (Exception e) {
        mTitleText.get().setText(R.string.no_response);
        mAuthorText.get().setText("");
        e.printStackTrace();
    }

In the above code mTitleText and mAuthorText are WeakReference instances and the use of the reference is used without checking if the object has been collected. I have much more experience in C, C++, C#, Javascript and languages other than Java. So there might be something I am missing here. But according to the documentation, this will return null and it is not inside of a larger try block. If it will not crash, then I have to wonder why a weak reference is required at all.

As a side note, I had posted other issues in the documentation relating to the source in this project. Those two issues were:

Naming conventions were not followed and variables with the scope level of a method were using class level member naming syntax. mVarName. When working through this in the tutorial, this was confusing and led me to place the code in the class instead of the function as I did not read the instructions well and assumed the code went in the class based on convention.
The documentation confuses the concept of an instance versus a reference (or handle). When getting a handle to a view with findViewById(...). Once again if you are looking at the complete code, this is obvious. But when reading instructions that say now create an instance of a TextView, it is initially confusing. Even worse, new developers who do not know the difference may learn an invalid vocabulary leading them to poor communication with other developers.

**Comment by daveb68x** [comment]
After thinking about it further, I realized that onPostExecute would not be called if the component had been collected.

**Comment by fatmahrazzaq** [comment]
How to pass a paragraph to using put Extra function with intents?
