### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by ghost** [google-developer-training/android-fundamentals-apps-v2#152]
**Describe the problem**
Inside (**1.2 Implement onStartJob()**) 3rd step should be Inside the **NotificationJobService.java** class instead of **onStartMethod()**, It is a bit misleading, Since we cann't define a method inside another method in java.

**In which lesson and step of the codelab can this issue be found?**
Lesson number: 3. Task 1: Implement a JobService 
step number: 1.2 Implement onStartJob() >> 3rd step

**Comment by riyasvmc** [comment]
A small error, but it is misleading the learners.
