### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by drokdev** [google-developer-training/android-fundamentals-apps-v2#173]
**Describe the problem**
Lesson describes a "textAlignment" option that doesn't exist.

**In which lesson and step of the codelab can this issue be found?**
Android fundamentals 01.2 Part A: Step 4.2

**How to reproduce?**
Open activity_main.xml
Open Attributes panel, look at Common Attributes tab
Try to find `textAlignment` attribute
It does not exist

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 30

**Additional information**
None

**codelab:** android-fundamentals

**Comment by drokdev** [comment]
This SHOULD say Java instead of Kotlin, I don't lknow how to change it though. Not sure if it matters or not.

**Comment by pau1a** [comment]
+1
