### ISSUE TITLE
Android Java Fundamentals codelab: 

### ISSUE THREAD

**Issue by pau1a** [google-developer-training/android-fundamentals-apps-v2#177]
**Describe the problem**
The Android fundamentals 04.1: Clickable images codelab is completely out of whack now that AS4.0.1 is out. The Basic Activity uses androidx and fragments and therefore makes no sense when a user creates a new app and tries to follow the lab

**In which lesson and step of the codelab can this issue be found?**
Android fundamentals 04.1: Clickable images

**How to reproduce?**
What are the exact steps to reproduce the problem?
Attempt the lab

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 30

**Additional information**
Add any other context about the problem here. N/A

**codelab:** android-fundamentals

**Comment by zakacat** [comment]
I was running into the same problem and I was able to go thru 4.5 RecyclerView by altering the Basic Activity on start up.
Mine also started with fragment files that I hardly know how to use and also a navigation layout which I have yet to even use.
I deleted these on start up:

-FirstFragment.java
-SecondFragment.java
-fragment_first.xml
-fragment_second.xml
-the navigation folder in res. (which contains only nav_graph.xml)
-the nav fragment layout in content_main.xml

This left me with a single activity with 2 layout files that housed a FAB button and a toolbar/appbar.

I was able to go through 4.5 with no problems.
