### ISSUE TITLE
Android Developer Fundamentals Course: Implicit Intents

### ISSUE THREAD

**Issue by soykan** [google-developer-training/android-fundamentals-apps-v2#188]
A clear and concise description of what the problem is:
Open website and open location don't work with current code in Android fundamentals 02.3: Implicit intents

This code doesn't start the activity only logs.

```
if (intent.resolveActivity(getPackageManager()) != null) {
            startActivity(intent);
        } else {
            Log.d("ImplicitIntents", "Can't handle this intent!");
        }
```

If I remove the if block, activity starts.
`startActivity(intent);`

I use Android Studio 4.0.1 . I am targeting API level 16.

Android Developer Fundamentals Course

**Comment by quocnb** [comment]
@soykan In android 11, Google added package visibility policy. Apps now have tighter control over viewing other apps. Your application will not be able to view or access applications outside of your application. 
All you need to do is add below code to your AndroidManifest.xml
```java
<queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
    </queries>
```
