### ISSUE TITLE
Data Not Retain In Room ViewModel LiveData

### ISSUE THREAD

**Issue by zawawimanja** [google-developer-training/android-fundamentals-apps-v2#19]
I try to kill the apps then go back into the apps but the data is not saved .Why?

**Comment by amberream** [comment]
Which codelab is this?  10.1 Part B shows you how to actually save the data.

https://codelabs.developers.google.com/codelabs/android-training-room-delete-data/index.html?index=..%2F..android-training#0

**Comment by zawawimanja** [comment]
Room update will be save the data. If you test other sample Room Sample & Room delete will not save the data.
