### ISSUE TITLE
Add style lint for naming conventions

### ISSUE THREAD

**Issue by vitiral** [google-developer-training/android-fundamentals-apps-v2#2]
According to the [style guide](https://source.android.com/setup/contribute/code-style#follow-field-naming-conventions), prefixing variables with `m` should only be done for "Non-public, non-static field names".

However, I found at least two cases in the same file where it is being used for local variables:
 - [first](https://github.com/google-developer-training/android-fundamentals-apps-v2/blob/master/RecyclerView/app/src/main/java/com/example/android/recyclerview/WordListAdapter.java#L102)
 - [second](https://github.com/google-developer-training/android-fundamentals-apps-v2/blob/master/RecyclerView/app/src/main/java/com/example/android/recyclerview/WordListAdapter.java#L121)

I'm not sure if a style lint can be added. The `m` confused me as a new android developer, and having it used inconsistently is even more confusing.

**Comment by daveb68x** [comment]
Yes please.  Looking at a small code snippet when naming conventions are not followed is confusing.  

The comments also confuse the concept of a reference and an instance in at least one place.    Saying create an instance of a class when you are in fact retrieving a reference by using findViewById  is confusing to anyone who thinks you are actually creating an instance until they evaluate the code.  I.e. the explanation you read before reviewing the code does not match the code and delay the acquisition of the lesson intending to be taught.

Other samples mixed configuration between three files where all three files needed to be kept in sync and was very error prone development.  While not critical to understanding the concept, it would be problematic if this code was used as sample/starter code for a real application.  If you are trying to follow what I am saying, it is basically that code should not be cyclical when it can be avoided.  The three tab/pager example is the one I am referring to.

It feels like a non developer (or at least a non experienced developer) created these samples.  While a non experienced developer is probably the best person to identify when a concept that would not need to be explained to a seasoned developer is glossed over, they can write confusing descriptions that delay effectiveness when they misuse conventions and vocabulary.  Perhaps have a senior developer review these applications before writing the tutorial around them.
