### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Chigiduba** [google-developer-training/android-fundamentals-apps-v2#245]
**Describe the problem**
there is no colorprimary color. I think it's not updated to newer versions of android studio

**In which lesson and step of the codelab can this issue be found?**
Android fundamentals 01.2 Part A: Your first interactive UI
Task 3 - change ui elements attributes
section 3.2

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. android studio 4.1.2

2. What API level are you targeting?
/

**Additional information**

**codelab:** android-fundamentals

**Comment by kentond18** [comment]
I have experienced the same issue going through the Android Fundamentals tutorials as a part of my uni coursework.
