### ISSUE TITLE
Android java Fundamentals codelab: 

### ISSUE THREAD

**Issue by Lokhc** [google-developer-training/android-fundamentals-apps-v2#287]
**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-fundamentals

**Comment by Lokhc** [comment]
Android Studio 4.1.2
API level: 25

startActivityForResult(intent, TEXT_REQUEST);

deprecated method .

[https://developer.android.com/codelabs/android-training-create-an-activity?index=..%2F..%2Fandroid-training#5](url)

**Comment by Sekisback** [comment]
https://youtu.be/qO3FFuBrT2E
