### ISSUE TITLE
Android Kotlin Fundamentals codelab (Java): 

### ISSUE THREAD

**Issue by JoseManuelAlmeidaPereira** [google-developer-training/android-fundamentals-apps-v2#299]
It is a suggestion and not a bug.
The course materials are Awesome for starting learning.
The suggestion is:
Could you considerer putting these courses in Github. Here is an example of a course: https://microsoft.github.io/IoT-For-Beginners/#/    

Please apologise if this is not the right way for communicating the suggestion.
Thanks again for the excellent quality materials

**Comment by mwaoh** [comment]
It's a good suggestion ...easier accessible  together with the code itself
