### ISSUE TITLE
Android Fundamentals codelab: 01.2Part B: The Layout Editor

### ISSUE THREAD

**Issue by akarastogiannis** [google-developer-training/android-fundamentals-apps-v2#349]
**Describe the problem**

The codelab tells the student to select the "Create Landscape Variation" button when they select the "Orientation Editor button" in the toolbar but the "Create Landscape Variation" button does not appear when you select the "Orientation Editor button". The student instead has to 
1. Navigate to the project tab and right click on "activity_main" folder.
2. Select New -> Layout Resource File.
3. Select "Orientation" in the Available Qualifiers section.
4. Click the two arrows (>>) to open up the Screen Orientation section.
5. Select "Landscape" in the Screen Orientation section.
6. Name the file "activity_main.xml" in the above File Name section.
7. Then click Ok.
8. Copy the xml code from the "activity_main.xml" and paste it in "activity_main.xml (land)" section.
9. Done.

**In which lesson and step of the codelab can this issue be found?**
-> Android Fundamentals 01.2 Part B: The Layout Editor,
->-> 3. Task 1: Create Layout Variants,
-> ->->1.2 Create a layout variant for horizontal orientation, 
->->->->Step 1 & 2.

**How to reproduce?**
What are the exact steps to reproduce the problem?
The tutorial appears to have some minor outdated instructions.

**Versions**
1. What version of Android Studio are you using?
Android Studio Chipmunk | 2021.2.1, built on April 28, 2022

10. What API level are you targeting?
32

**Additional information**
N/A, But I just wanted to say amazing course so far, great job designing it!

**codelab:** android-fundamentals

**Comment by Desperationis** [comment]
It appears the button has been moved to another option in the toolbar. Instead of being in the orientation tab, it is in the tab that says `activity_main.xml`. Click `Create Landscape Quantifier` and it does the same thing.
