### ISSUE TITLE
Android Java Fundamentals codelab: 

### ISSUE THREAD

**Issue by Viltrimite** [google-developer-training/android-fundamentals-apps-v2#351]
**Describe the problem**
Codelab instructions aren't leading to an expected error which is  "the digit (0) in the show_count TextView element is too low for the horizontal orientation—too close to the Count button." Also, the variant creation tool location has not been updated.

**In which lesson and step of the codelab can this issue be found?**
Lesson 1.2 Part B step 1.2.

**How to reproduce?**
Follow all previous codelab instructions up to lesson 1.2 Part B

**Versions**
1. Version: 2021.2.1
2. API target level: 33

**Additional information**
The qualifiers button has not been added to the layout editor toolbar, which is where the variant creation tool is now located.

**codelab:** android-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
