### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by dajong** [google-developer-training/android-fundamentals-apps-v2#353]
**Describe the problem**
A clear and concise description of what the problem is.
Instead of clicking that orientation for preview button, we should create landscape variation here.
![Screenshot 2022-09-21 at 11 04 00](https://user-images.githubusercontent.com/48896947/191476780-3ff8dca3-f4c5-403f-99c1-3a5afec59444.png)

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
https://developer.android.com/codelabs/android-training-layout-editor-part-b#2
Android Fundamentals 01.2 Part B
1.2 Create a layout variant for horizontal orientation
when it is showing how to create landscape variation.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2021.3.1
3. What API level are you targeting?
33
**Additional information**

**codelab:** android-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
