### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by atownnoob** [google-developer-training/android-fundamentals-apps-v2#356]
**Describe the problem**
A clear and concise description of what the problem is.

For Java codelab. As written, implicit intent to open browser link will fail ie. browser will not open in AVD emulator with API > 30 (Android 11).

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

https://developer.android.com/codelabs/android-training-activity-with-implicit-intent?index=..%2F..%2Fandroid-training#3
Implicit Intents 02.3, Task 2, Step 6

**How to reproduce?**
What are the exact steps to reproduce the problem?

Implement the code exactly as described in the codelab.

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

1. Chipmunk, 2021.2.1 Patch 2
2. API Level 30

**Additional information**

Issue resolved by adding following to the manifest .xml

    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:scheme="http"/>
        </intent>
    </queries>

**codelab:** android-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
