### ISSUE TITLE
Codelabs for Android Developer Fundamentals: Unit 1 Get Started: Lesson 3.2

### ISSUE THREAD

**Issue by evuazeze** [google-developer-training/android-fundamentals-apps-v2#357]
**Describe the problem**
A clear and concise description of what the problem is.

The first coding challenge implies that the division of floating point numbers by zero results in an IllegalArgumentException but this is not the case according to the Java specifications(https://docs.oracle.com/javase/specs/jls/se14/html/jls-15.html#jls-15.17.2). Division of a floating point number can result in POSITIVE_INFINITY, NEGATIVE_INFINITY or NaN but not an IllegalArgumentException. 

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

Lesson 3.2. Coding challenge

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
