### ISSUE TITLE
Android Java Fundamentals codelab: 

### ISSUE THREAD

**Issue by JTremblettBVC** [google-developer-training/android-fundamentals-apps-v2#358]
**Describe the problem**
center_vertical doesn't center text

**In which lesson and step of the codelab can this issue be found?**
01.2 Part B 2.4.

**How to reproduce?**
all I did was change the gravity to center_vertical and the number immediately snapped to the left

**Versions**
1. What version of Android Studio are you using?
2. 2022.1.1
3. What API level are you targeting?
33
**Additional information**

**codelab:** android-fundamentals

![image](https://user-images.githubusercontent.com/97629125/213098945-35577db7-cf0d-4f41-8f91-6d7de57c0a70.png)

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
