### ISSUE TITLE
Android Kotlin Fundamentals codelab: Not uppdated.

### ISSUE THREAD

**Issue by J3ti** [google-developer-training/android-fundamentals-apps-v2#359]
**Describe the problem**
A clear and concise description of what the problem is.
The template looks different

**In which lesson and step of the codelab can this issue be found?**
[Android fundamentals 04.1: Clickable images](https://developer.android.com/codelabs/android-training-clickable-images?index=..%2F..%2Fandroid-training)
Step3
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?
can't follow the instructions after 

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
