### ISSUE TITLE
Android Kotlin Fundamentals codelab:  None of the instructions worked

### ISSUE THREAD

**Issue by PachoSur** [google-developer-training/android-fundamentals-apps-v2#360]
**Describe the problem**
After following all instructions and additions, NONE of the worked. No messages appeared in Logcat. No actions when rotating render, etc.

**In which lesson and step of the codelab can this issue be found?**
02.2 LifeCycle lesson.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 8.1 6.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    documentation.show.toolbar=true

2. What API level are you targeting?
31

**Additional information**

**codelab:** android-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
