### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by michelejiang** [google-developer-training/android-fundamentals-apps-v2#361]
**Describe the problem**
mistyped '@' attribute's value

**In which lesson and step of the codelab can this issue be found?**
Lesson 01.3 step 3

**How to reproduce?**
android:background="@color/colorPrimary"

**Versions**
1. What version of Android Studio are you using? 2022.1.1 patch 2
3. What API level are you targeting?

**Additional information**
the '@' should be removed
android:background="color/colorPrimary"

**codelab:** android-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
