### ISSUE TITLE
Android Java Fundamentals codelab: 

### ISSUE THREAD

**Issue by igorzeck** [google-developer-training/android-fundamentals-apps-v2#362]
The tutorial says to put in activity_main.xml the following: android:background="@color/colorPrimary" when the correct would most certainly be: android:background="?attr/colorPrimary"

01.3 + 3

Using the most recent version of Android Studio released for Windows as of today (27/03/23)

It's not abug per say, I just don't know where to report this error. Might also be that the tutorial uses an older version.

**codelab:** android-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
