### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by MarkPuchalaII** [google-developer-training/android-fundamentals-apps-v2#366]
**Describe the problem**
This asks me to add a line,  `    private static final String ACTION_CUSTOM_BROADCAST =
            BuildConfig.APPLICATION_ID + ".ACTION_CUSTOM_BROADCAST";`
, but doing so gives the error, "Cannot resolve symbol 'BuildConfig'".
I've tried multiple solutions to add this `BuildConfig` attribute to my gradle files, but nothing has helped.

**In which lesson and step of the codelab can this issue be found?**
Lesson 7.3 + step 4.

**How to reproduce?**
Create a constant member variable in either your MainActivity and your CustomReceiver class. You'll use this variable as the broadcast Intent action. `private static final String ACTION_CUSTOM_BROADCAST = BuildConfig.APPLICATION_ID + ".ACTION_CUSTOM_BROADCAST";`

**Versions**
1. What version of Android Studio are you using? Android Studio Flamingo | 2022.2.1 Patch 2
2. What API level are you targeting?     minSdk 26

**Additional information**
This is basically a broken tutorial for me until I can find a solution to the BuildConfig problem. 
I can see `defaultConfig {
        applicationId "com.example.powerreceiver"` in my build.gradle file if I could just access it. I just don't know how.
**codelab:** android-fundamentals

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
