### ISSUE TITLE
Why is AsyncTaskLoader still a part of the codelabs?

### ISSUE THREAD

**Issue by Zhuinden** [google-developer-training/android-fundamentals-apps-v2#5]
It is deprecated in favor of using AAC (ViewModel + LiveData).

I don't know why it's in the fundamentals at all.

**Comment by EbrahimKaram** [comment]
@Zhuinden Do you know a proper tutorial on how to use ViewModel and LiveData?

> It is deprecated in favor of using AAC (ViewModel + LiveData).
> 
> I don't know why it's in the fundamentals at all.

**Comment by Zhuinden** [comment]
See https://codelabs.developers.google.com/codelabs/android-lifecycles/#2
