### ISSUE TITLE
Wrong Color Code 

### ISSUE THREAD

**Issue by f-fuchs** [google-developer-training/android-fundamentals-apps-v2#6]
Android fundamentals 01.2 Part A: Your first interactive UI

In Task 4 it says to set the background color to #FFF00, but thats not a valid hex value, it should be #FFF000 I think.

https://codelabs.developers.google.com/codelabs/android-training-layout-editor-part-a/index.html?index=..%2F..%2Fandroid-training#5

**Comment by hengin** [comment]
Indeed. The code contains the (nigh indistinguishable) value `#FFFF00`. https://github.com/google-developer-training/android-fundamentals-apps-v2/blob/3064cf5aa8f248122a951757b071282d8ef44b50/HelloToast/app/src/main/res/layout/activity_main.xml#L64

**Comment by GeneAndGoogle** [comment]
FIxed!
