### ISSUE TITLE
Counter value gets reset to 0 upon changing the orientation of the device for project (Hello Toast)

### ISSUE THREAD

**Issue by bhaskar253** [google-developer-training/android-fundamentals-apps-v2#7]
While running the application developed in **Hello Toast project** on the android emulator if we click Count button several times and then we change the orientation from portrait mode to landscape mode the value displayed in TextView gets reset to 0.

**Comment by hengin** [comment]
This happens because Android implements orientation changes by destroying and recreating activities. Can be annoying to deal with.

Relevant documentation: https://developer.android.com/guide/topics/resources/runtime-changes

**Comment by vikilinho** [comment]
I also noticed similar issue when running the app on my device. The documentation has provided the answer to the issue.
