### ISSUE TITLE
Android fundamentals 04.1

### ISSUE THREAD

**Issue by stephen-fayer** [google-developer-training/android-fundamentals-apps-v2#70]
**Describe the problem**
A clear and concise description of what the problem is.
The codelab-  Android fundamentals 04.1 does not take into account the basic activity template now uses fragments so is almost imposible to complete as the student has no knowedge of fragments or where to insert the code.
**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Android fundamentals 04.1
**How to reproduce?**
What are the exact steps to reproduce the problem?
Added graphical elements to fragment_first.xml but need to add the displayToast to MainActivity.java
and the onClick methods to FirstFragment.java they cannot find the displayToast.
**Versions**
1. What version of Android Studio are you using? 3.6.2
2. What API level are you targeting? 29

**Additional information**
Either teach fragments before this of change this codelab to use the fragments and teach them here
**codelab:** android-fundamentals
Android fundamentals 04.1

**Comment by zakacat** [comment]
I was running into the same problem and I was able to go thru 4.5 RecyclerView by altering the Basic Activity on start up.
Mine also started with fragment files that I hardly know how to use and also a navigation layout which I have yet to even use.
I deleted these on start up:

-FirstFragment.java
-SecondFragment.java
-fragment_first.xml
-fragment_second.xml
-the navigation folder in res. (which contains only nav_graph.xml)
-the nav fragment layout in content_main.xml

This left me with a single activity with 2 layout files that housed a FAB button and a toolbar/appbar.

I was able to go through 4.5 with no problems.
