### ISSUE TITLE
Fix the error

### ISSUE THREAD

**Issue by timemake** [google-developer-training/android-fundamentals-apps-v2#8]
#1 Error on Tutorial:
Android fundamentals 07.1: AsyncTask 
5. Delete the app:layout_constraintRight_toRightOf and app:layout_constraintTop_toTopOf attributes. ==> this is wrong.

#2 Source code error:
When the device is rotated after clicking the button the text is "Napping..." forever. Please wakeup and show the correct text message.

**Comment by paramitapal** [comment]
As mentioned by timemake, there are errors... Please take below steps to rectify the same:

#1 The textView layout code should include only  app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="parent". Then  delete rest of the constarints.
#2 The asynctask needs to start again by adding the line startTask(mTextView); inside savedInstanceState to show the correct message during configuration change.
