### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by sbaadsgaard** [google-developer-training/android-fundamentals-apps-v2#95]
**Describe the problem**
The text says that division by 0 should result in an error (specifically IllegalArgumentException). However, the reusult is Double.POSITIVE_INFINITY. This is also reflected in the solution code where it asserts that it is indeed equal to infinity. It is very confusing that there is this mismatch between the text and the actual behaviour, and the solution code.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Android fundamentals 03.2: Unit tests task 2

**How to reproduce?**
What are the exact steps to reproduce the problem?
enter 0 as the second number in the app

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

1) version 3.6.2
2) 27

**Additional information**

This is in java

**codelab:** android-fundamentals

**Comment by graffiti75** [comment]
For me it worked following those steps:

1) At `Calculator.java` I changed the signature of method `div()` to:
```
/**
 * Divide operation
 */
public double div(double firstOperand, double secondOperand) {
    return firstOperand / secondOperand;
}
```

2) Then I updated this call on `MainActivity.java`, just to prevent the code to not compile.

3) Finally, at `CalculatorTest.java`, I changed the method `divByZeroThrows()` to:

```
/*
 * Tests for divide by zero; must throw IllegalArgumentException.
 */
// @Test(expected = IllegalArgumentException.class)
@Test(expected = ArithmeticException.class)
public void divByZeroThrows() {
    mCalculator.div(32d, 0d);
}
```

Please try this and let me know if works!
